#include <nds.h>
#include <stdio.h>
#include <errno.h>
#include <dlfcn.h>
#include <filesystem.h>
#include <fat.h>

// This file contains pointers to the data: `forest_townTiles`, `forest_townMap`
// and `forest_townPal`. It also contains the size of everything:
// `forest_townTilesLen`, etc.
#include "../graphics/forest_town.h"

// Headers autogenerated for each PNG file inside GFXDIRS in the Makefile
#include "../graphics/ball.h"
#include "../graphics/city.h"
#include "../graphics/neon.h"

#include "../data/teapot_bin.h"

class BlockDSExamples
{
public:
    void InputTests();
    void BGScroll2D();
    void LayerMovement();
    void Object3D();

private:
    void wait_forever(void)
    {
        while (1)
            swiWaitForVBlank();
    }
};