#pragma once

enum SKL_TONE
{
    SKL_TONE_AUTHOR,
    SKL_TONE_CARING,
    SKL_TONE_CASUAL,
    SKL_TONE_CHATTY,
    SLK_TONE_CHEER,
    SKL_TONE_CONSERV,
    SKL_TONE_DIRECT,
    SKL_TONE_EDGY,
    SKL_TONE_ENTHUS,
    SKL_TONE_FORMAL,
    SKL_TONE_FRANK,
    SKL_TONE_FRIEND,
    SKL_TONE_HUMOR,
    SKL_TONE_INFORM,
    SKL_TONE_IRREV,
    SKL_TONE_PASSION,
    SKL_TONE_PLAY,
    SKL_TONE_PROFESS,
    SKL_TONE_PROVOC,
    SKL_TONE_QUIRKY,
    SKL_TONE_RESON,
    SKL_TONE_RESPECT,
    SKL_TONE_ROM,
    SKL_TONE_SAR,
    SKL_TONE_SER,
    SKL_TONE_SNARKY,
    SKL_TONE_SYMPATH,
    SKL_TONE_TRENDY,
    SKL_TONE_TRUST,
    SKL_TONE_UNAPOLO,
    SKL_TONE_WITTY

};

enum SKL_TOPIC
{
    SKL_TOPIC_HISTORY,
    SKL_TOPIC_PEOPLE,
    SKL_TOPIC_UNDGR,
    SKL_TOPIC_CRIME,
    SKL_TOPIC_MAGIC
};