enum TONE_TYPE
{
    TONE_TYPE_POSITIVE,
    TONE_TYPE_NEUTRAL,
    TONE_TYPE_NEGATIVE

};

enum TONE_SKILL
{
    TONE_SKILL_AUTHOR,
    TONE_SKILL_CARING,
    TONE_SKILL_CASUAL,
    TONE_SKILL_CHATTY,
    TONE_SKILL_CHEER,
    TONE_SKILL_CONSERV,
    TONE_SKILL_DIRECT,
    TONE_SKILL_EDGY,
    TONE_SKILL_ENTHUS,
    TONE_SKILL_FORMAL,
    TONE_SKILL_FRANK,
    TONE_SKILL_FRIEND,
    TONE_SKILL_HUMOR,
    TONE_SKILL_INFORM,
    TONE_SKILL_IRREV,
    TONE_SKILL_PASSION,
    TONE_SKILL_PLAY,
    TONE_SKILL_PROFESS,
    TONE_SKILL_PROVOC,
    TONE_SKILL_QUIRKY,
    TONE_SKILL_RESON,
    TONE_SKILL_RESPECT,
    TONE_SKILL_ROM,
    TONE_SKILL_SAR,
    TONE_SKILL_SER,
    TONE_SKILL_SNARKY,
    TONE_SKILL_SYMPATH,
    TONE_SKILL_TRENDY,
    TONE_SKILL_TRUST,
    TONE_SKILL_UNAPOLO,
    TONE_SKILL_WITTY
};

struct Tone
{
    public:
    TONE_SKILL m_skill;
    TONE_TYPE m_type;

    Tone(TONE_SKILL skill, TONE_TYPE type) :
        m_skill{skill},
        m_type{type}
    {}
    ~Tone() = default;
};